package Experiment;

public class ExceptionHandling {
static int divide(int a,int b)
{
	int i = a/b;
	return i;
}
	public static void main(String[] args)
	{
		int a=2,b=2;
		try {
			System.out.println("Attempting to divide "+a+" by "+b+".");
			int result = divide(a,b);
			System.out.println("Result : "+result);
		}catch(ArithmeticException ex)
		{
			System.out.print("An Error occurred"+ex.getMessage());
		}
		System.out.println("Execution completed");
	}
}
